#
#  This file is part of ComposerButtonBonanza.
#
#  Copyright 2025 Matt Marjanovic
#
#  ComposerButtonBonanza is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as published
#  by the Free Software Foundation; either version 3 of the License, or any
#  later version.
#
#  ComposerButtonBonanza is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
#  Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with ComposerButtonBonanza.  If not, see <https://www.gnu.org/licenses/>.
#
buttons:
  type: objects
  schema:
    name: button
    identifier: name
    properties:
      name:
        type: string
        required: true
      svg_icon:
        type: string
      nonIcon:
        type: string
      title:
        type: string
      popupHover:
        type: string
      action:
        required: true
        type: enum
        choices:
          - surround
          - list
          - insert
          - toggleGroup
      prefix:
        type: string
      suffix:
        type: string
      lineMode:
        type: enum
        choices:
          - inline
          - multiline
          - block
      exampleText:
        type: string
      groupName:
        type: string
      startHidden:
        type: boolean
  default:
    - name: styledText
      svg_icon: palette
      title: "Styled Text"
      exampleText: "styled text"
      action: surround
      prefix: '<div style="color: red; transform: rotate(10deg); background: linear-gradient(45deg, blue, green);">'
      suffix: "</div>"
      lineMode: inline
    - name: inserted
      svg_icon: highlighter
      title: "Mark Inserted"
      exampleText: "inserted text"
      action: surround
      prefix: "<ins>"
      suffix: "</ins>"
      lineMode: inline
    - name: deleted
      svg_icon: highlighter
      title: "Mark Deleted"
      exampleText: "deleted text"
      action: surround
      prefix: "<del>"
      suffix: "</del>"
      lineMode: inline
    - name: toggleBonanza
      svg_icon: cubes-stacked
      title: "More Buttons"
      popupHover: "Show/hide additional markup buttons in the toolbar"
      action: toggleGroup
      groupName: bonanza
      startHidden: true

svg_icons:
  type: list
  list_type: compact
  default: cubes-stacked|highlighter|palette

translations:
  type: objects
  schema:
    name: locale
    identifier: locale
    properties:
      locale:
        type: string
        required: true
      translations:
        type: objects
        schema:
          name: translation
          identifier: key
          properties:
            key:
              type: string
              required: true
            value:
              type: string
  default: []

layout:
  type: list
  default: EXTRAS|styledText,,bonanza|inserted,,bonanza|deleted,,bonanza|GEARMENU|toggleBonanza
